name: pdf_thumbnail
description: Thumbnail viewer for PDF files. Supports Android and iOS. Simply add widget and give the file path.
version: 0.1.6+1
homepage: https://github.com/mirkancal/pdf_thumbnail
documentation: https://github.com/mirkancal/pdf_thumbnail/blob/main/README.md

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  pdf_image_renderer: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
